server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&seUniucode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root


